// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contest struct {
	ID              pgtype.UUID
	CreatedByUserID int64
	Title           string
	Description     string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ContestChatMessage struct {
	ID        pgtype.UUID
	ContestID pgtype.UUID
	UserID    int64
	Text      string
	IsSystem  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ContestComment struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        int64
	Text          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ContestParticipant struct {
	ID             pgtype.UUID
	ContestID      pgtype.UUID
	UserID         int64
	PetName        string
	PetDescription string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ContestParticipantPhoto struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	Url           string
	ThumbUrl      *string
	CreatedAt     pgtype.Timestamptz
}

type ContestParticipantVideo struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	Url           string
	CreatedAt     pgtype.Timestamptz
}

type ContestVote struct {
	ID            pgtype.UUID
	ContestID     pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	UserID    int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type UserAuthProvider struct {
	UserID      int64
	ProviderUid string
	Provider    string
	Name        *string
}
