// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contest struct {
	ID                  pgtype.UUID
	CreatedByUserID     int64
	Title               string
	Description         string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Tier                string
	CoverUrl            string
	RegistrationEndsAt  pgtype.Timestamptz
	VotingStartsAt      pgtype.Timestamptz
	VotingEndsAt        pgtype.Timestamptz
	RequireAcceptance   bool
	PublicVotingEnabled bool
	Tagline             string
	RulesUrl            string
	PrizeText           string
	LogoUrl             string
	ThemeColor          string
	SponsorName         string
	SponsorLogoUrl      string
	SponsorUrl          string
	CtaLabelOverride    string
}

type ContestChatMessage struct {
	ID        pgtype.UUID
	ContestID pgtype.UUID
	UserID    int64
	Text      string
	IsSystem  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ContestComment struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        int64
	Text          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ContestJuryCriterium struct {
	ID          pgtype.UUID
	ContestID   pgtype.UUID
	Title       string
	Description string
	ScaleMin    int32
	ScaleMax    int32
	ScaleStep   int32
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

type ContestNomination struct {
	ID          pgtype.UUID
	ContestID   pgtype.UUID
	Title       string
	Description string
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

type ContestParticipant struct {
	ID                  pgtype.UUID
	ContestID           pgtype.UUID
	UserID              int64
	PetName             string
	PetDescription      string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	RegistrationAnswers []byte
}

type ContestRegistrationField struct {
	ID          pgtype.UUID
	ContestID   pgtype.UUID
	SortOrder   int32
	Label       string
	FieldType   string
	Required    bool
	EnumOptions []byte
	CreatedAt   pgtype.Timestamptz
}

type ContestParticipantPhoto struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	Url           string
	ThumbUrl      *string
	CreatedAt     pgtype.Timestamptz
	Position      int32
}

type ContestParticipantVideo struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	Url           string
	CreatedAt     pgtype.Timestamptz
}

type ContestVote struct {
	ID            pgtype.UUID
	ContestID     pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        int64
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type PhotoLike struct {
	ID        pgtype.UUID
	PhotoID   pgtype.UUID
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type UserAuthProvider struct {
	UserID      int64
	ProviderUid string
	Provider    string
	Name        *string
}
