// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contest struct {
	ID              pgtype.UUID
	CreatedByUserID int64
	Title           string
	Description     string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Tier            string
	CoverUrl        string
	// Автоматический переход draft → registration при наступлении момента
	RegistrationStartsAt pgtype.Timestamptz
	// Автоматический переход registration → voting; момент окончания приёма заявок
	VotingStartsAt pgtype.Timestamptz
	// Автоматический переход voting → finished
	VotingEndsAt      pgtype.Timestamptz
	RequireAcceptance bool
	// Если true — участники могут получать голоса посетителей
	PublicVotingEnabled bool
	// Если true — используются критерии жюри и состав жюри
	JuryVotingEnabled bool
	Tagline           string
	RulesUrl          string
	PrizeText         string
	LogoUrl           string
	ThemeColor        string
	SponsorName       string
	SponsorLogoUrl    string
	SponsorUrl        string
	CtaLabelOverride  string
	// Домены e-mail (разделители: перевод строки, запятая), нижний регистр; пусто — участвовать может любой авторизованный пользователь.
	ParticipantAllowedEmailDomains string
	// IANA TZ для ввода расписания организатором (даты в API по-прежнему UTC)
	ScheduleTimezone string
	// Автоматический переход draft → publication при наступлении момента
	PublicationStartsAt pgtype.Timestamptz
}

type ContestChatMessage struct {
	ID        pgtype.UUID
	ContestID pgtype.UUID
	UserID    int64
	Text      string
	IsSystem  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ContestComment struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        int64
	Text          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ContestJuryCriterium struct {
	ID          pgtype.UUID
	ContestID   pgtype.UUID
	Title       string
	Description string
	ScaleMin    int32
	ScaleMax    int32
	ScaleStep   int32
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

type ContestJuryMember struct {
	ID        pgtype.UUID
	ContestID pgtype.UUID
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type ContestJuryScore struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	CriterionID   pgtype.UUID
	UserID        int64
	Score         int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ContestNomination struct {
	ID          pgtype.UUID
	ContestID   pgtype.UUID
	Title       string
	Description string
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
	// Минимальное число фото в заявке для этой номинации (по умолчанию 1).
	MinPhotoCount int32
}

type ContestParticipantPhoto struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	Url           string
	ThumbUrl      *string
	CreatedAt     pgtype.Timestamptz
	Position      int32
}

type ContestParticipantVideo struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	Url           string
	CreatedAt     pgtype.Timestamptz
}

type ContestRegistrationField struct {
	ID          pgtype.UUID
	ContestID   pgtype.UUID
	SortOrder   int32
	Label       string
	FieldType   string
	Required    bool
	EnumOptions []byte
	CreatedAt   pgtype.Timestamptz
}

type ContestVote struct {
	ID             pgtype.UUID
	ContestID      pgtype.UUID
	ParticipantID  pgtype.UUID
	UserID         int64
	NominationID   pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	NominationSlot pgtype.UUID
}

type PhotoLike struct {
	ID        pgtype.UUID
	PhotoID   pgtype.UUID
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

type User struct {
	UserID    int64
	Name      string
	CreatedAt pgtype.Timestamptz
	Email     *string
	Role      string
}

type UserAuthProvider struct {
	UserID      int64
	ProviderUid string
	Provider    string
	Name        *string
}
