// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipantPhoto = `-- name: AddParticipantPhoto :one

INSERT INTO contest_participant_photos (id, participant_id, url, thumb_url, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, participant_id, url, thumb_url, created_at, position
`

type AddParticipantPhotoParams struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	Url           string
	ThumbUrl      *string
	Position      int32
}

// Contest Participant Photos
func (q *Queries) AddParticipantPhoto(ctx context.Context, arg *AddParticipantPhotoParams) (*ContestParticipantPhoto, error) {
	row := q.db.QueryRow(ctx, addParticipantPhoto,
		arg.ID,
		arg.ParticipantID,
		arg.Url,
		arg.ThumbUrl,
		arg.Position,
	)
	var i ContestParticipantPhoto
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Url,
		&i.ThumbUrl,
		&i.CreatedAt,
		&i.Position,
	)
	return &i, err
}

const addUserAuthProviders = `-- name: AddUserAuthProviders :one
INSERT INTO user_auth_providers (user_id, provider_uid, provider, name)
VALUES ($1, $2, $3, $4)
RETURNING user_id, provider_uid, provider, name
`

type AddUserAuthProvidersParams struct {
	UserID      int64
	ProviderUid string
	Provider    string
	Name        *string
}

func (q *Queries) AddUserAuthProviders(ctx context.Context, arg *AddUserAuthProvidersParams) (*UserAuthProvider, error) {
	row := q.db.QueryRow(ctx, addUserAuthProviders,
		arg.UserID,
		arg.ProviderUid,
		arg.Provider,
		arg.Name,
	)
	var i UserAuthProvider
	err := row.Scan(
		&i.UserID,
		&i.ProviderUid,
		&i.Provider,
		&i.Name,
	)
	return &i, err
}

const countChatMessages = `-- name: CountChatMessages :one
SELECT count(1) FROM contest_chat_messages
WHERE contest_id = $1
`

func (q *Queries) CountChatMessages(ctx context.Context, contestID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChatMessages, contestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommentsByParticipant = `-- name: CountCommentsByParticipant :one
SELECT count(1) FROM contest_comments
WHERE participant_id = $1
`

func (q *Queries) CountCommentsByParticipant(ctx context.Context, participantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByParticipant, participantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContestJuryMembers = `-- name: CountContestJuryMembers :one
SELECT count(*)::bigint FROM contest_jury_members WHERE contest_id = $1
`

func (q *Queries) CountContestJuryMembers(ctx context.Context, contestID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countContestJuryMembers, contestID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countContests = `-- name: CountContests :one
SELECT count(1) FROM contests
WHERE (COALESCE($1::text, '') = '' OR status = $1)
`

func (q *Queries) CountContests(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countContests, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNominationsByContest = `-- name: CountNominationsByContest :one
SELECT count(1) FROM contest_nominations WHERE contest_id = $1
`

func (q *Queries) CountNominationsByContest(ctx context.Context, contestID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNominationsByContest, contestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countParticipantsByContest = `-- name: CountParticipantsByContest :one
SELECT COUNT(*)::bigint
FROM contest_participants cp
WHERE cp.contest_id = $1
  AND (
    cp.submission_status = 'accepted'
    OR $2::boolean = true
    OR (
      $3::bigint IS NOT NULL
      AND cp.user_id = $3::bigint
    )
  )
  AND (
    $4::text = 'all'
    OR ($4::text = 'none' AND cp.nomination_id IS NULL)
    OR (
      $4::text = 'id'
      AND cp.nomination_id = $5::uuid
    )
  )
  AND (
    NOT $6::boolean
    OR $3::bigint IS NULL
    OR (
      (SELECT COUNT(*)::int FROM contest_jury_criteria cjc WHERE cjc.contest_id = cp.contest_id) = 0
    )
    OR (
      (SELECT COUNT(*)::int FROM contest_jury_scores j
       WHERE j.participant_id = cp.id AND j.user_id = $3::bigint
      ) < (
      SELECT COUNT(*)::int FROM contest_jury_criteria cjc2 WHERE cjc2.contest_id = cp.contest_id
      )
    )
  )
  AND (
    $7::text = 'all'
    OR (
      $3::bigint IS NOT NULL
      AND cp.user_id = $3::bigint
    )
  )
  AND (
    $8::text = 'all'
    OR ($8::text = 'accepted' AND cp.submission_status = 'accepted')
    OR ($8::text = 'pending' AND cp.submission_status = 'pending')
    OR ($8::text = 'rejected' AND cp.submission_status = 'rejected')
    OR (
      $8::text = 'non_accepted'
      AND cp.submission_status IN ('pending', 'rejected')
    )
  )
  AND (
    NOT $9::boolean
    OR EXISTS (
      SELECT 1 FROM contest_votes v
      WHERE v.contest_id = cp.contest_id
        AND v.participant_id = cp.id
        AND v.user_id = $3::bigint
    )
  )
`

type CountParticipantsByContestParams struct {
	ContestID            pgtype.UUID
	IncludeAll           bool
	ViewerUserID         *int64
	NominationFilterMode string
	NominationFilterID   pgtype.UUID
	JuryUnscoredOnly     bool
	ParticipantScope     string
	SubmissionFilter     string
	VotedByViewerOnly    bool
}

func (q *Queries) CountParticipantsByContest(ctx context.Context, arg *CountParticipantsByContestParams) (int64, error) {
	row := q.db.QueryRow(ctx, countParticipantsByContest,
		arg.ContestID,
		arg.IncludeAll,
		arg.ViewerUserID,
		arg.NominationFilterMode,
		arg.NominationFilterID,
		arg.JuryUnscoredOnly,
		arg.ParticipantScope,
		arg.SubmissionFilter,
		arg.VotedByViewerOnly,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPhotoLikes = `-- name: CountPhotoLikes :one
SELECT count(1) FROM photo_likes
WHERE photo_id = $1
`

func (q *Queries) CountPhotoLikes(ctx context.Context, photoID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotoLikes, photoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSystemAdmins = `-- name: CountSystemAdmins :one
SELECT count(*)::bigint AS count FROM users WHERE role = 'system_admin'
`

func (q *Queries) CountSystemAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSystemAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint AS count FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVotesByContest = `-- name: CountVotesByContest :one
SELECT count(1) FROM contest_votes
WHERE contest_id = $1
`

func (q *Queries) CountVotesByContest(ctx context.Context, contestID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVotesByContest, contestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVotesByContests = `-- name: CountVotesByContests :many
SELECT contest_id, count(1) as vote_count FROM contest_votes
WHERE contest_id = ANY($1::uuid[])
GROUP BY contest_id
`

type CountVotesByContestsRow struct {
	ContestID pgtype.UUID
	VoteCount int64
}

func (q *Queries) CountVotesByContests(ctx context.Context, dollar_1 []pgtype.UUID) ([]*CountVotesByContestsRow, error) {
	rows, err := q.db.Query(ctx, countVotesByContests, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CountVotesByContestsRow
	for rows.Next() {
		var i CountVotesByContestsRow
		if err := rows.Scan(&i.ContestID, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countVotesByParticipant = `-- name: CountVotesByParticipant :one
SELECT count(1) FROM contest_votes
WHERE participant_id = $1
`

func (q *Queries) CountVotesByParticipant(ctx context.Context, participantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVotesByParticipant, participantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatMessage = `-- name: CreateChatMessage :one

INSERT INTO contest_chat_messages (id, contest_id, user_id, text, is_system)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, contest_id, user_id, text, is_system, created_at, updated_at
`

type CreateChatMessageParams struct {
	ID        pgtype.UUID
	ContestID pgtype.UUID
	UserID    int64
	Text      string
	IsSystem  bool
}

// Contest Chat Messages
func (q *Queries) CreateChatMessage(ctx context.Context, arg *CreateChatMessageParams) (*ContestChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ID,
		arg.ContestID,
		arg.UserID,
		arg.Text,
		arg.IsSystem,
	)
	var i ContestChatMessage
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.Text,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO contest_comments (id, participant_id, user_id, text)
VALUES ($1, $2, $3, $4)
RETURNING id, participant_id, user_id, text, created_at, updated_at
`

type CreateCommentParams struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        int64
	Text          string
}

// Contest Comments
func (q *Queries) CreateComment(ctx context.Context, arg *CreateCommentParams) (*ContestComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.ParticipantID,
		arg.UserID,
		arg.Text,
	)
	var i ContestComment
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createContest = `-- name: CreateContest :one

INSERT INTO contests (id, created_by_user_id, title, description, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_by_user_id, title, description, status, created_at, updated_at, tier, cover_url, registration_starts_at, voting_starts_at, voting_ends_at, require_acceptance, public_voting_enabled, jury_voting_enabled, tagline, rules_url, prize_text, logo_url, theme_color, sponsor_name, sponsor_logo_url, sponsor_url, cta_label_override, participant_allowed_email_domains, schedule_timezone
`

type CreateContestParams struct {
	ID              pgtype.UUID
	CreatedByUserID int64
	Title           string
	Description     string
	Status          string
}

// Contests
func (q *Queries) CreateContest(ctx context.Context, arg *CreateContestParams) (*Contest, error) {
	row := q.db.QueryRow(ctx, createContest,
		arg.ID,
		arg.CreatedByUserID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.CoverUrl,
		&i.RegistrationStartsAt,
		&i.VotingStartsAt,
		&i.VotingEndsAt,
		&i.RequireAcceptance,
		&i.PublicVotingEnabled,
		&i.JuryVotingEnabled,
		&i.Tagline,
		&i.RulesUrl,
		&i.PrizeText,
		&i.LogoUrl,
		&i.ThemeColor,
		&i.SponsorName,
		&i.SponsorLogoUrl,
		&i.SponsorUrl,
		&i.CtaLabelOverride,
		&i.ParticipantAllowedEmailDomains,
		&i.ScheduleTimezone,
	)
	return &i, err
}

const createNomination = `-- name: CreateNomination :one

INSERT INTO contest_nominations (id, contest_id, title, description, sort_order, min_photo_count)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, contest_id, title, description, sort_order, created_at, min_photo_count
`

type CreateNominationParams struct {
	ID            pgtype.UUID
	ContestID     pgtype.UUID
	Title         string
	Description   string
	SortOrder     int32
	MinPhotoCount int32
}

// Contest nominations (категории; без шкал — шкалы только у критериев конкурса)
func (q *Queries) CreateNomination(ctx context.Context, arg *CreateNominationParams) (*ContestNomination, error) {
	row := q.db.QueryRow(ctx, createNomination,
		arg.ID,
		arg.ContestID,
		arg.Title,
		arg.Description,
		arg.SortOrder,
		arg.MinPhotoCount,
	)
	var i ContestNomination
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.MinPhotoCount,
	)
	return &i, err
}

const createParticipant = `-- name: CreateParticipant :one

INSERT INTO contest_participants (id, contest_id, user_id, pet_name, pet_description, registration_answers, nomination_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, contest_id, user_id, pet_name, pet_description, created_at, updated_at, registration_answers, nomination_id, submission_status, submission_comment
`

type CreateParticipantParams struct {
	ID                  pgtype.UUID
	ContestID           pgtype.UUID
	UserID              int64
	PetName             string
	PetDescription      string
	RegistrationAnswers []byte
	NominationID        pgtype.UUID
}

type CreateParticipantRow struct {
	ID                  pgtype.UUID
	ContestID           pgtype.UUID
	UserID              int64
	PetName             string
	PetDescription      string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	RegistrationAnswers []byte
	NominationID        pgtype.UUID
	SubmissionStatus    string
	SubmissionComment   *string
}

// Contest Participants
func (q *Queries) CreateParticipant(ctx context.Context, arg *CreateParticipantParams) (*CreateParticipantRow, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.ID,
		arg.ContestID,
		arg.UserID,
		arg.PetName,
		arg.PetDescription,
		arg.RegistrationAnswers,
		arg.NominationID,
	)
	var i CreateParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.PetName,
		&i.PetDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationAnswers,
		&i.NominationID,
		&i.SubmissionStatus,
		&i.SubmissionComment,
	)
	return &i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (name, email)
VALUES (
    $1,
    NULLIF(btrim($2::text), '')
)
RETURNING user_id, name, created_at, email, role
`

type CreateUserParams struct {
	Name  string
	Email string
}

// Users
func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.Email,
		&i.Role,
	)
	return &i, err
}

const deleteChatMessage = `-- name: DeleteChatMessage :one
DELETE FROM contest_chat_messages
WHERE id = $1 AND user_id = $2 AND is_system = FALSE
RETURNING contest_id
`

type DeleteChatMessageParams struct {
	ID     pgtype.UUID
	UserID int64
}

func (q *Queries) DeleteChatMessage(ctx context.Context, arg *DeleteChatMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteChatMessage, arg.ID, arg.UserID)
	var contest_id pgtype.UUID
	err := row.Scan(&contest_id)
	return contest_id, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM contest_comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const deleteCommentsByParticipant = `-- name: DeleteCommentsByParticipant :exec
DELETE FROM contest_comments
WHERE participant_id = $1
`

func (q *Queries) DeleteCommentsByParticipant(ctx context.Context, participantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommentsByParticipant, participantID)
	return err
}

const deleteContest = `-- name: DeleteContest :exec
DELETE FROM contests
WHERE id = $1
`

func (q *Queries) DeleteContest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContest, id)
	return err
}

const deleteContestJuryMember = `-- name: DeleteContestJuryMember :exec
DELETE FROM contest_jury_members
WHERE contest_id = $1 AND user_id = $2
`

type DeleteContestJuryMemberParams struct {
	ContestID pgtype.UUID
	UserID    int64
}

func (q *Queries) DeleteContestJuryMember(ctx context.Context, arg *DeleteContestJuryMemberParams) error {
	_, err := q.db.Exec(ctx, deleteContestJuryMember, arg.ContestID, arg.UserID)
	return err
}

const deleteContestVoteByUserAndNomination = `-- name: DeleteContestVoteByUserAndNomination :one
DELETE FROM contest_votes
WHERE contest_id = $1 AND user_id = $2
  AND nomination_id IS NOT DISTINCT FROM $3::uuid
RETURNING participant_id
`

type DeleteContestVoteByUserAndNominationParams struct {
	ContestID    pgtype.UUID
	UserID       int64
	NominationID pgtype.UUID
}

func (q *Queries) DeleteContestVoteByUserAndNomination(ctx context.Context, arg *DeleteContestVoteByUserAndNominationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteContestVoteByUserAndNomination, arg.ContestID, arg.UserID, arg.NominationID)
	var participant_id pgtype.UUID
	err := row.Scan(&participant_id)
	return participant_id, err
}

const deleteJuryCriteriaByContest = `-- name: DeleteJuryCriteriaByContest :exec
DELETE FROM contest_jury_criteria WHERE contest_id = $1
`

func (q *Queries) DeleteJuryCriteriaByContest(ctx context.Context, contestID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJuryCriteriaByContest, contestID)
	return err
}

const deleteNomination = `-- name: DeleteNomination :exec
DELETE FROM contest_nominations WHERE id = $1
`

func (q *Queries) DeleteNomination(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNomination, id)
	return err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM contest_participants
WHERE id = $1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteParticipant, id)
	return err
}

const deleteParticipantPhoto = `-- name: DeleteParticipantPhoto :exec
DELETE FROM contest_participant_photos
WHERE id = $1
`

func (q *Queries) DeleteParticipantPhoto(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteParticipantPhoto, id)
	return err
}

const deleteParticipantVideo = `-- name: DeleteParticipantVideo :exec
DELETE FROM contest_participant_videos
WHERE participant_id = $1
`

func (q *Queries) DeleteParticipantVideo(ctx context.Context, participantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteParticipantVideo, participantID)
	return err
}

const deletePhotoLike = `-- name: DeletePhotoLike :exec
DELETE FROM photo_likes
WHERE photo_id = $1 AND user_id = $2
`

type DeletePhotoLikeParams struct {
	PhotoID pgtype.UUID
	UserID  int64
}

func (q *Queries) DeletePhotoLike(ctx context.Context, arg *DeletePhotoLikeParams) error {
	_, err := q.db.Exec(ctx, deletePhotoLike, arg.PhotoID, arg.UserID)
	return err
}

const deleteRegistrationFieldsByContest = `-- name: DeleteRegistrationFieldsByContest :exec
DELETE FROM contest_registration_fields WHERE contest_id = $1
`

func (q *Queries) DeleteRegistrationFieldsByContest(ctx context.Context, contestID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegistrationFieldsByContest, contestID)
	return err
}

const deleteVotesByParticipant = `-- name: DeleteVotesByParticipant :exec
DELETE FROM contest_votes
WHERE participant_id = $1
`

func (q *Queries) DeleteVotesByParticipant(ctx context.Context, participantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVotesByParticipant, participantID)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, participant_id, user_id, text, created_at, updated_at FROM contest_comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (*ContestComment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i ContestComment
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getContestByID = `-- name: GetContestByID :one
SELECT id, created_by_user_id, title, description, status, created_at, updated_at, tier, cover_url, registration_starts_at, voting_starts_at, voting_ends_at, require_acceptance, public_voting_enabled, jury_voting_enabled, tagline, rules_url, prize_text, logo_url, theme_color, sponsor_name, sponsor_logo_url, sponsor_url, cta_label_override, participant_allowed_email_domains, schedule_timezone FROM contests WHERE id = $1
`

func (q *Queries) GetContestByID(ctx context.Context, id pgtype.UUID) (*Contest, error) {
	row := q.db.QueryRow(ctx, getContestByID, id)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.CoverUrl,
		&i.RegistrationStartsAt,
		&i.VotingStartsAt,
		&i.VotingEndsAt,
		&i.RequireAcceptance,
		&i.PublicVotingEnabled,
		&i.JuryVotingEnabled,
		&i.Tagline,
		&i.RulesUrl,
		&i.PrizeText,
		&i.LogoUrl,
		&i.ThemeColor,
		&i.SponsorName,
		&i.SponsorLogoUrl,
		&i.SponsorUrl,
		&i.CtaLabelOverride,
		&i.ParticipantAllowedEmailDomains,
		&i.ScheduleTimezone,
	)
	return &i, err
}

const getContestVoteForUserNominationSlot = `-- name: GetContestVoteForUserNominationSlot :one
SELECT id, contest_id, participant_id, user_id, nomination_id, created_at, updated_at, nomination_slot FROM contest_votes
WHERE contest_id = $1 AND user_id = $2
  AND nomination_id IS NOT DISTINCT FROM $3::uuid
`

type GetContestVoteForUserNominationSlotParams struct {
	ContestID    pgtype.UUID
	UserID       int64
	NominationID pgtype.UUID
}

func (q *Queries) GetContestVoteForUserNominationSlot(ctx context.Context, arg *GetContestVoteForUserNominationSlotParams) (*ContestVote, error) {
	row := q.db.QueryRow(ctx, getContestVoteForUserNominationSlot, arg.ContestID, arg.UserID, arg.NominationID)
	var i ContestVote
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ParticipantID,
		&i.UserID,
		&i.NominationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NominationSlot,
	)
	return &i, err
}

const getMaxPhotoPositionByParticipant = `-- name: GetMaxPhotoPositionByParticipant :one
SELECT COALESCE(MAX(position), 0) AS max_position
FROM contest_participant_photos
WHERE participant_id = $1
`

func (q *Queries) GetMaxPhotoPositionByParticipant(ctx context.Context, participantID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxPhotoPositionByParticipant, participantID)
	var max_position interface{}
	err := row.Scan(&max_position)
	return max_position, err
}

const getNominationByContest = `-- name: GetNominationByContest :one
SELECT id, contest_id, title, description, sort_order, created_at, min_photo_count FROM contest_nominations
WHERE id = $1 AND contest_id = $2
`

type GetNominationByContestParams struct {
	ID        pgtype.UUID
	ContestID pgtype.UUID
}

func (q *Queries) GetNominationByContest(ctx context.Context, arg *GetNominationByContestParams) (*ContestNomination, error) {
	row := q.db.QueryRow(ctx, getNominationByContest, arg.ID, arg.ContestID)
	var i ContestNomination
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.MinPhotoCount,
	)
	return &i, err
}

const getParticipantByContestUserAndNomination = `-- name: GetParticipantByContestUserAndNomination :one
SELECT
    cp.id,
    cp.contest_id,
    cp.user_id,
    COALESCE(u.name, 'Пользователь ' || cp.user_id::text) AS user_name,
    cp.pet_name,
    cp.pet_description,
    cp.registration_answers,
    cp.nomination_id,
    cp.submission_status,
    cp.submission_comment,
    cp.created_at,
    cp.updated_at
FROM contest_participants cp
LEFT JOIN users u ON u.user_id = cp.user_id
WHERE cp.contest_id = $1 AND cp.user_id = $2
  AND cp.nomination_id IS NOT DISTINCT FROM $3::uuid
`

type GetParticipantByContestUserAndNominationParams struct {
	ContestID    pgtype.UUID
	UserID       int64
	NominationID pgtype.UUID
}

type GetParticipantByContestUserAndNominationRow struct {
	ID                  pgtype.UUID
	ContestID           pgtype.UUID
	UserID              int64
	UserName            string
	PetName             string
	PetDescription      string
	RegistrationAnswers []byte
	NominationID        pgtype.UUID
	SubmissionStatus    string
	SubmissionComment   *string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetParticipantByContestUserAndNomination(ctx context.Context, arg *GetParticipantByContestUserAndNominationParams) (*GetParticipantByContestUserAndNominationRow, error) {
	row := q.db.QueryRow(ctx, getParticipantByContestUserAndNomination, arg.ContestID, arg.UserID, arg.NominationID)
	var i GetParticipantByContestUserAndNominationRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.UserName,
		&i.PetName,
		&i.PetDescription,
		&i.RegistrationAnswers,
		&i.NominationID,
		&i.SubmissionStatus,
		&i.SubmissionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getParticipantByID = `-- name: GetParticipantByID :one
SELECT
    cp.id,
    cp.contest_id,
    cp.user_id,
    COALESCE(u.name, 'Пользователь ' || cp.user_id::text) AS user_name,
    cp.pet_name,
    cp.pet_description,
    cp.registration_answers,
    cp.nomination_id,
    cp.submission_status,
    cp.submission_comment,
    cp.created_at,
    cp.updated_at
FROM contest_participants cp
LEFT JOIN users u ON u.user_id = cp.user_id
WHERE cp.id = $1
`

type GetParticipantByIDRow struct {
	ID                  pgtype.UUID
	ContestID           pgtype.UUID
	UserID              int64
	UserName            string
	PetName             string
	PetDescription      string
	RegistrationAnswers []byte
	NominationID        pgtype.UUID
	SubmissionStatus    string
	SubmissionComment   *string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetParticipantByID(ctx context.Context, id pgtype.UUID) (*GetParticipantByIDRow, error) {
	row := q.db.QueryRow(ctx, getParticipantByID, id)
	var i GetParticipantByIDRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.UserName,
		&i.PetName,
		&i.PetDescription,
		&i.RegistrationAnswers,
		&i.NominationID,
		&i.SubmissionStatus,
		&i.SubmissionComment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPhotoLikeByUser = `-- name: GetPhotoLikeByUser :one
SELECT id, photo_id, user_id, created_at FROM photo_likes
WHERE photo_id = $1 AND user_id = $2
`

type GetPhotoLikeByUserParams struct {
	PhotoID pgtype.UUID
	UserID  int64
}

func (q *Queries) GetPhotoLikeByUser(ctx context.Context, arg *GetPhotoLikeByUserParams) (*PhotoLike, error) {
	row := q.db.QueryRow(ctx, getPhotoLikeByUser, arg.PhotoID, arg.UserID)
	var i PhotoLike
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.UserID,
		&i.CreatedAt,
	)
	return &i, err
}

const getPhotosByParticipantID = `-- name: GetPhotosByParticipantID :many
SELECT id, participant_id, url, thumb_url, created_at, position FROM contest_participant_photos
WHERE participant_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) GetPhotosByParticipantID(ctx context.Context, participantID pgtype.UUID) ([]*ContestParticipantPhoto, error) {
	rows, err := q.db.Query(ctx, getPhotosByParticipantID, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ContestParticipantPhoto
	for rows.Next() {
		var i ContestParticipantPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Url,
			&i.ThumbUrl,
			&i.CreatedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAuthProvidersByProviderUid = `-- name: GetUserAuthProvidersByProviderUid :one
SELECT user_id, provider_uid, provider, name FROM user_auth_providers
WHERE provider_uid = $1 AND provider = $2
`

type GetUserAuthProvidersByProviderUidParams struct {
	ProviderUid string
	Provider    string
}

func (q *Queries) GetUserAuthProvidersByProviderUid(ctx context.Context, arg *GetUserAuthProvidersByProviderUidParams) (*UserAuthProvider, error) {
	row := q.db.QueryRow(ctx, getUserAuthProvidersByProviderUid, arg.ProviderUid, arg.Provider)
	var i UserAuthProvider
	err := row.Scan(
		&i.UserID,
		&i.ProviderUid,
		&i.Provider,
		&i.Name,
	)
	return &i, err
}

const getUserAuthProvidersByUserID = `-- name: GetUserAuthProvidersByUserID :many
SELECT user_id, provider_uid, provider, name FROM user_auth_providers
WHERE user_id = $1
`

func (q *Queries) GetUserAuthProvidersByUserID(ctx context.Context, userID int64) ([]*UserAuthProvider, error) {
	rows, err := q.db.Query(ctx, getUserAuthProvidersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserAuthProvider
	for rows.Next() {
		var i UserAuthProvider
		if err := rows.Scan(
			&i.UserID,
			&i.ProviderUid,
			&i.Provider,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, name, created_at, email, role FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.Email,
		&i.Role,
	)
	return &i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM users WHERE user_id = $1
`

func (q *Queries) GetUserRole(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, userID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getVideoByParticipantID = `-- name: GetVideoByParticipantID :one
SELECT id, participant_id, url, created_at FROM contest_participant_videos
WHERE participant_id = $1
`

func (q *Queries) GetVideoByParticipantID(ctx context.Context, participantID pgtype.UUID) (*ContestParticipantVideo, error) {
	row := q.db.QueryRow(ctx, getVideoByParticipantID, participantID)
	var i ContestParticipantVideo
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Url,
		&i.CreatedAt,
	)
	return &i, err
}

const insertContestJuryMember = `-- name: InsertContestJuryMember :one
INSERT INTO contest_jury_members (id, contest_id, user_id)
VALUES ($1, $2, $3)
RETURNING id, contest_id, user_id, created_at
`

type InsertContestJuryMemberParams struct {
	ID        pgtype.UUID
	ContestID pgtype.UUID
	UserID    int64
}

func (q *Queries) InsertContestJuryMember(ctx context.Context, arg *InsertContestJuryMemberParams) (*ContestJuryMember, error) {
	row := q.db.QueryRow(ctx, insertContestJuryMember, arg.ID, arg.ContestID, arg.UserID)
	var i ContestJuryMember
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.CreatedAt,
	)
	return &i, err
}

const insertJuryCriterion = `-- name: InsertJuryCriterion :one
INSERT INTO contest_jury_criteria (
    id, contest_id, title, description, scale_min, scale_max, scale_step, sort_order
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, contest_id, title, description, scale_min, scale_max, scale_step, sort_order, created_at
`

type InsertJuryCriterionParams struct {
	ID          pgtype.UUID
	ContestID   pgtype.UUID
	Title       string
	Description string
	ScaleMin    int32
	ScaleMax    int32
	ScaleStep   int32
	SortOrder   int32
}

func (q *Queries) InsertJuryCriterion(ctx context.Context, arg *InsertJuryCriterionParams) (*ContestJuryCriterium, error) {
	row := q.db.QueryRow(ctx, insertJuryCriterion,
		arg.ID,
		arg.ContestID,
		arg.Title,
		arg.Description,
		arg.ScaleMin,
		arg.ScaleMax,
		arg.ScaleStep,
		arg.SortOrder,
	)
	var i ContestJuryCriterium
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Title,
		&i.Description,
		&i.ScaleMin,
		&i.ScaleMax,
		&i.ScaleStep,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return &i, err
}

const insertRegistrationField = `-- name: InsertRegistrationField :one
INSERT INTO contest_registration_fields (
    id, contest_id, sort_order, label, field_type, required, enum_options
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, contest_id, sort_order, label, field_type, required, enum_options, created_at
`

type InsertRegistrationFieldParams struct {
	ID          pgtype.UUID
	ContestID   pgtype.UUID
	SortOrder   int32
	Label       string
	FieldType   string
	Required    bool
	EnumOptions []byte
}

func (q *Queries) InsertRegistrationField(ctx context.Context, arg *InsertRegistrationFieldParams) (*ContestRegistrationField, error) {
	row := q.db.QueryRow(ctx, insertRegistrationField,
		arg.ID,
		arg.ContestID,
		arg.SortOrder,
		arg.Label,
		arg.FieldType,
		arg.Required,
		arg.EnumOptions,
	)
	var i ContestRegistrationField
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.SortOrder,
		&i.Label,
		&i.FieldType,
		&i.Required,
		&i.EnumOptions,
		&i.CreatedAt,
	)
	return &i, err
}

const isContestJuryMember = `-- name: IsContestJuryMember :one
SELECT EXISTS (
    SELECT 1 FROM contest_jury_members jm
    WHERE jm.contest_id = $1 AND jm.user_id = $2
)
`

type IsContestJuryMemberParams struct {
	ContestID pgtype.UUID
	UserID    int64
}

func (q *Queries) IsContestJuryMember(ctx context.Context, arg *IsContestJuryMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isContestJuryMember, arg.ContestID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAcceptedParticipantScoresForContest = `-- name: ListAcceptedParticipantScoresForContest :many
SELECT
    cp.id AS participant_id,
    cp.nomination_id,
    COALESCE(vc.vote_cnt, 0)::bigint AS vote_cnt,
    COALESCE(js.jury_sum, 0)::bigint AS jury_sum
FROM contest_participants cp
LEFT JOIN (
    SELECT participant_id, COUNT(*)::bigint AS vote_cnt
    FROM contest_votes
    GROUP BY participant_id
) vc ON vc.participant_id = cp.id
LEFT JOIN (
    SELECT participant_id, SUM(score)::bigint AS jury_sum
    FROM contest_jury_scores
    GROUP BY participant_id
) js ON js.participant_id = cp.id
WHERE cp.contest_id = $1 AND cp.submission_status = 'accepted'
`

type ListAcceptedParticipantScoresForContestRow struct {
	ParticipantID pgtype.UUID
	NominationID  pgtype.UUID
	VoteCnt       int64
	JurySum       int64
}

func (q *Queries) ListAcceptedParticipantScoresForContest(ctx context.Context, contestID pgtype.UUID) ([]*ListAcceptedParticipantScoresForContestRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedParticipantScoresForContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAcceptedParticipantScoresForContestRow
	for rows.Next() {
		var i ListAcceptedParticipantScoresForContestRow
		if err := rows.Scan(
			&i.ParticipantID,
			&i.NominationID,
			&i.VoteCnt,
			&i.JurySum,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT 
    ccm.id,
    ccm.contest_id,
    ccm.user_id,
    ccm.text,
    ccm.is_system,
    ccm.created_at,
    ccm.updated_at,
    COALESCE(u.name, 'Пользователь ' || ccm.user_id::text) as user_name
FROM contest_chat_messages ccm
LEFT JOIN users u ON u.user_id = ccm.user_id
WHERE ccm.contest_id = $1
ORDER BY ccm.created_at ASC
LIMIT $2 OFFSET $3
`

type ListChatMessagesParams struct {
	ContestID pgtype.UUID
	Limit     int32
	Offset    int32
}

type ListChatMessagesRow struct {
	ID        pgtype.UUID
	ContestID pgtype.UUID
	UserID    int64
	Text      string
	IsSystem  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UserName  string
}

func (q *Queries) ListChatMessages(ctx context.Context, arg *ListChatMessagesParams) ([]*ListChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChatMessages, arg.ContestID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListChatMessagesRow
	for rows.Next() {
		var i ListChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.Text,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByParticipant = `-- name: ListCommentsByParticipant :many
SELECT
    cc.id,
    cc.participant_id,
    cc.user_id,
    cc.text,
    cc.created_at,
    cc.updated_at,
    COALESCE(u.name, 'Пользователь ' || cc.user_id::text) AS user_name
FROM contest_comments cc
LEFT JOIN users u ON u.user_id = cc.user_id
WHERE cc.participant_id = $1
ORDER BY cc.created_at ASC
LIMIT $2 OFFSET $3
`

type ListCommentsByParticipantParams struct {
	ParticipantID pgtype.UUID
	Limit         int32
	Offset        int32
}

type ListCommentsByParticipantRow struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        int64
	Text          string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	UserName      string
}

func (q *Queries) ListCommentsByParticipant(ctx context.Context, arg *ListCommentsByParticipantParams) ([]*ListCommentsByParticipantRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByParticipant, arg.ParticipantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCommentsByParticipantRow
	for rows.Next() {
		var i ListCommentsByParticipantRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestJuryMembersWithNames = `-- name: ListContestJuryMembersWithNames :many

SELECT
    jm.id,
    jm.contest_id,
    jm.user_id,
    jm.created_at,
    u.name AS user_name
FROM contest_jury_members jm
INNER JOIN users u ON u.user_id = jm.user_id
WHERE jm.contest_id = $1
ORDER BY jm.created_at ASC
`

type ListContestJuryMembersWithNamesRow struct {
	ID        pgtype.UUID
	ContestID pgtype.UUID
	UserID    int64
	CreatedAt pgtype.Timestamptz
	UserName  string
}

// Contest jury members
func (q *Queries) ListContestJuryMembersWithNames(ctx context.Context, contestID pgtype.UUID) ([]*ListContestJuryMembersWithNamesRow, error) {
	rows, err := q.db.Query(ctx, listContestJuryMembersWithNames, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListContestJuryMembersWithNamesRow
	for rows.Next() {
		var i ListContestJuryMembersWithNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestJuryScoresByParticipantAndUser = `-- name: ListContestJuryScoresByParticipantAndUser :many
SELECT id, participant_id, criterion_id, user_id, score, created_at, updated_at
FROM contest_jury_scores
WHERE participant_id = $1 AND user_id = $2
ORDER BY criterion_id
`

type ListContestJuryScoresByParticipantAndUserParams struct {
	ParticipantID pgtype.UUID
	UserID        int64
}

func (q *Queries) ListContestJuryScoresByParticipantAndUser(ctx context.Context, arg *ListContestJuryScoresByParticipantAndUserParams) ([]*ContestJuryScore, error) {
	rows, err := q.db.Query(ctx, listContestJuryScoresByParticipantAndUser, arg.ParticipantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ContestJuryScore
	for rows.Next() {
		var i ContestJuryScore
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.CriterionID,
			&i.UserID,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestVotesByUser = `-- name: ListContestVotesByUser :many
SELECT id, contest_id, participant_id, user_id, nomination_id, created_at, updated_at, nomination_slot FROM contest_votes
WHERE contest_id = $1 AND user_id = $2
ORDER BY nomination_slot ASC
`

type ListContestVotesByUserParams struct {
	ContestID pgtype.UUID
	UserID    int64
}

func (q *Queries) ListContestVotesByUser(ctx context.Context, arg *ListContestVotesByUserParams) ([]*ContestVote, error) {
	rows, err := q.db.Query(ctx, listContestVotesByUser, arg.ContestID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ContestVote
	for rows.Next() {
		var i ContestVote
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ParticipantID,
			&i.UserID,
			&i.NominationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NominationSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContests = `-- name: ListContests :many
SELECT id, created_by_user_id, title, description, status, created_at, updated_at, tier, cover_url, registration_starts_at, voting_starts_at, voting_ends_at, require_acceptance, public_voting_enabled, jury_voting_enabled, tagline, rules_url, prize_text, logo_url, theme_color, sponsor_name, sponsor_logo_url, sponsor_url, cta_label_override, participant_allowed_email_domains, schedule_timezone FROM contests
WHERE (COALESCE($1::text, '') = '' OR status = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListContestsParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListContests(ctx context.Context, arg *ListContestsParams) ([]*Contest, error) {
	rows, err := q.db.Query(ctx, listContests, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Contest
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.CoverUrl,
			&i.RegistrationStartsAt,
			&i.VotingStartsAt,
			&i.VotingEndsAt,
			&i.RequireAcceptance,
			&i.PublicVotingEnabled,
			&i.JuryVotingEnabled,
			&i.Tagline,
			&i.RulesUrl,
			&i.PrizeText,
			&i.LogoUrl,
			&i.ThemeColor,
			&i.SponsorName,
			&i.SponsorLogoUrl,
			&i.SponsorUrl,
			&i.CtaLabelOverride,
			&i.ParticipantAllowedEmailDomains,
			&i.ScheduleTimezone,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestsForStatusAutomation = `-- name: ListContestsForStatusAutomation :many
SELECT id, created_by_user_id, title, description, status, created_at, updated_at, tier, cover_url, registration_starts_at, voting_starts_at, voting_ends_at, require_acceptance, public_voting_enabled, jury_voting_enabled, tagline, rules_url, prize_text, logo_url, theme_color, sponsor_name, sponsor_logo_url, sponsor_url, cta_label_override, participant_allowed_email_domains, schedule_timezone FROM contests
WHERE status IN ('draft', 'publication', 'registration', 'voting')
ORDER BY id
`

func (q *Queries) ListContestsForStatusAutomation(ctx context.Context) ([]*Contest, error) {
	rows, err := q.db.Query(ctx, listContestsForStatusAutomation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Contest
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByUserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.CoverUrl,
			&i.RegistrationStartsAt,
			&i.VotingStartsAt,
			&i.VotingEndsAt,
			&i.RequireAcceptance,
			&i.PublicVotingEnabled,
			&i.JuryVotingEnabled,
			&i.Tagline,
			&i.RulesUrl,
			&i.PrizeText,
			&i.LogoUrl,
			&i.ThemeColor,
			&i.SponsorName,
			&i.SponsorLogoUrl,
			&i.SponsorUrl,
			&i.CtaLabelOverride,
			&i.ParticipantAllowedEmailDomains,
			&i.ScheduleTimezone,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJuryCriteriaByContest = `-- name: ListJuryCriteriaByContest :many

SELECT id, contest_id, title, description, scale_min, scale_max, scale_step, sort_order, created_at FROM contest_jury_criteria
WHERE contest_id = $1
ORDER BY sort_order ASC, created_at ASC
`

// Contest jury criteria (общие для всего конкурса)
func (q *Queries) ListJuryCriteriaByContest(ctx context.Context, contestID pgtype.UUID) ([]*ContestJuryCriterium, error) {
	rows, err := q.db.Query(ctx, listJuryCriteriaByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ContestJuryCriterium
	for rows.Next() {
		var i ContestJuryCriterium
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.Title,
			&i.Description,
			&i.ScaleMin,
			&i.ScaleMax,
			&i.ScaleStep,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNominationsByContest = `-- name: ListNominationsByContest :many
SELECT id, contest_id, title, description, sort_order, created_at, min_photo_count FROM contest_nominations
WHERE contest_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListNominationsByContest(ctx context.Context, contestID pgtype.UUID) ([]*ContestNomination, error) {
	rows, err := q.db.Query(ctx, listNominationsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ContestNomination
	for rows.Next() {
		var i ContestNomination
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.MinPhotoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByContest = `-- name: ListParticipantsByContest :many
SELECT
    cp.id,
    cp.contest_id,
    cp.user_id,
    COALESCE(u.name, 'Пользователь ' || cp.user_id::text) AS user_name,
    cp.pet_name,
    cp.pet_description,
    cp.registration_answers,
    cp.nomination_id,
    cp.submission_status,
    cp.submission_comment,
    cp.created_at,
    cp.updated_at
FROM contest_participants cp
LEFT JOIN users u ON u.user_id = cp.user_id
LEFT JOIN (
    SELECT participant_id, COUNT(*)::bigint AS vote_cnt
    FROM contest_votes
    GROUP BY participant_id
) vc ON vc.participant_id = cp.id
WHERE cp.contest_id = $1
  AND (
    cp.submission_status = 'accepted'
    OR $2::boolean = true
    OR (
      $3::bigint IS NOT NULL
      AND cp.user_id = $3::bigint
    )
  )
  AND (
    $4::text = 'all'
    OR ($4::text = 'none' AND cp.nomination_id IS NULL)
    OR (
      $4::text = 'id'
      AND cp.nomination_id = $5::uuid
    )
  )
  AND (
    NOT $6::boolean
    OR $3::bigint IS NULL
    OR (
      (SELECT COUNT(*)::int FROM contest_jury_criteria cjc WHERE cjc.contest_id = cp.contest_id) = 0
    )
    OR (
      (SELECT COUNT(*)::int FROM contest_jury_scores j
       WHERE j.participant_id = cp.id AND j.user_id = $3::bigint
      ) < (
      SELECT COUNT(*)::int FROM contest_jury_criteria cjc2 WHERE cjc2.contest_id = cp.contest_id
      )
    )
  )
  AND (
    $7::text = 'all'
    OR (
      $3::bigint IS NOT NULL
      AND cp.user_id = $3::bigint
    )
  )
  AND (
    $8::text = 'all'
    OR ($8::text = 'accepted' AND cp.submission_status = 'accepted')
    OR ($8::text = 'pending' AND cp.submission_status = 'pending')
    OR ($8::text = 'rejected' AND cp.submission_status = 'rejected')
    OR (
      $8::text = 'non_accepted'
      AND cp.submission_status IN ('pending', 'rejected')
    )
  )
  AND (
    NOT $9::boolean
    OR EXISTS (
      SELECT 1 FROM contest_votes v
      WHERE v.contest_id = cp.contest_id
        AND v.participant_id = cp.id
        AND v.user_id = $3::bigint
    )
  )
ORDER BY
  CASE WHEN $10::boolean THEN COALESCE(vc.vote_cnt, 0::bigint) ELSE 0::bigint END DESC,
  cp.created_at ASC
LIMIT $12::int OFFSET $11::int
`

type ListParticipantsByContestParams struct {
	ContestID            pgtype.UUID
	IncludeAll           bool
	ViewerUserID         *int64
	NominationFilterMode string
	NominationFilterID   pgtype.UUID
	JuryUnscoredOnly     bool
	ParticipantScope     string
	SubmissionFilter     string
	VotedByViewerOnly    bool
	OrderByVotes         bool
	ListOffset           int32
	ListLimit            int32
}

type ListParticipantsByContestRow struct {
	ID                  pgtype.UUID
	ContestID           pgtype.UUID
	UserID              int64
	UserName            string
	PetName             string
	PetDescription      string
	RegistrationAnswers []byte
	NominationID        pgtype.UUID
	SubmissionStatus    string
	SubmissionComment   *string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) ListParticipantsByContest(ctx context.Context, arg *ListParticipantsByContestParams) ([]*ListParticipantsByContestRow, error) {
	rows, err := q.db.Query(ctx, listParticipantsByContest,
		arg.ContestID,
		arg.IncludeAll,
		arg.ViewerUserID,
		arg.NominationFilterMode,
		arg.NominationFilterID,
		arg.JuryUnscoredOnly,
		arg.ParticipantScope,
		arg.SubmissionFilter,
		arg.VotedByViewerOnly,
		arg.OrderByVotes,
		arg.ListOffset,
		arg.ListLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListParticipantsByContestRow
	for rows.Next() {
		var i ListParticipantsByContestRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.UserName,
			&i.PetName,
			&i.PetDescription,
			&i.RegistrationAnswers,
			&i.NominationID,
			&i.SubmissionStatus,
			&i.SubmissionComment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotoLikesByPhotos = `-- name: ListPhotoLikesByPhotos :many
SELECT id, photo_id, user_id, created_at
FROM photo_likes
WHERE photo_id = ANY($1::uuid[]) AND user_id = $2
`

type ListPhotoLikesByPhotosParams struct {
	Column1 []pgtype.UUID
	UserID  int64
}

func (q *Queries) ListPhotoLikesByPhotos(ctx context.Context, arg *ListPhotoLikesByPhotosParams) ([]*PhotoLike, error) {
	rows, err := q.db.Query(ctx, listPhotoLikesByPhotos, arg.Column1, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*PhotoLike
	for rows.Next() {
		var i PhotoLike
		if err := rows.Scan(
			&i.ID,
			&i.PhotoID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationFieldsByContest = `-- name: ListRegistrationFieldsByContest :many

SELECT id, contest_id, sort_order, label, field_type, required, enum_options, created_at
FROM contest_registration_fields
WHERE contest_id = $1
ORDER BY sort_order ASC, created_at ASC
`

// Contest registration fields (поля заявки участника)
func (q *Queries) ListRegistrationFieldsByContest(ctx context.Context, contestID pgtype.UUID) ([]*ContestRegistrationField, error) {
	rows, err := q.db.Query(ctx, listRegistrationFieldsByContest, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ContestRegistrationField
	for rows.Next() {
		var i ContestRegistrationField
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.SortOrder,
			&i.Label,
			&i.FieldType,
			&i.Required,
			&i.EnumOptions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffCommentNotificationsForUser = `-- name: ListStaffCommentNotificationsForUser :many
SELECT
    cp.id AS participant_id,
    cp.contest_id,
    c.title AS contest_title,
    cp.pet_name,
    COUNT(cc.id)::bigint AS unread_count,
    MAX(cc.created_at)::timestamptz AS latest_comment_at,
    (
        SELECT LEFT(cc3.text, 220)
        FROM contest_comments cc3
        INNER JOIN users u3 ON u3.user_id = cc3.user_id
        WHERE cc3.participant_id = cp.id
          AND cc3.user_id <> cp.user_id
          AND (
              c.created_by_user_id = cc3.user_id
              OR u3.role IN ('contest_admin', 'system_admin')
          )
          AND cc3.created_at > COALESCE(cp.owner_last_read_staff_comment_at, '-infinity'::timestamptz)
        ORDER BY cc3.created_at DESC
        LIMIT 1
    ) AS latest_comment_preview
FROM contest_participants cp
INNER JOIN contests c ON c.id = cp.contest_id
INNER JOIN contest_comments cc ON cc.participant_id = cp.id
INNER JOIN users u ON u.user_id = cc.user_id
WHERE cp.user_id = $1
  AND cc.user_id <> cp.user_id
  AND (
      c.created_by_user_id = cc.user_id
      OR u.role IN ('contest_admin', 'system_admin')
  )
  AND cc.created_at > COALESCE(cp.owner_last_read_staff_comment_at, '-infinity'::timestamptz)
GROUP BY cp.id, cp.contest_id, c.title, c.created_by_user_id, cp.pet_name, cp.user_id, cp.owner_last_read_staff_comment_at
HAVING COUNT(cc.id) > 0
ORDER BY MAX(cc.created_at) DESC
`

type ListStaffCommentNotificationsForUserRow struct {
	ParticipantID        pgtype.UUID
	ContestID            pgtype.UUID
	ContestTitle         string
	PetName              string
	UnreadCount          int64
	LatestCommentAt      pgtype.Timestamptz
	LatestCommentPreview string
}

func (q *Queries) ListStaffCommentNotificationsForUser(ctx context.Context, userID int64) ([]*ListStaffCommentNotificationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listStaffCommentNotificationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListStaffCommentNotificationsForUserRow
	for rows.Next() {
		var i ListStaffCommentNotificationsForUserRow
		if err := rows.Scan(
			&i.ParticipantID,
			&i.ContestID,
			&i.ContestTitle,
			&i.PetName,
			&i.UnreadCount,
			&i.LatestCommentAt,
			&i.LatestCommentPreview,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many
SELECT
  u.user_id,
  u.name,
  u.email,
  u.created_at,
  u.role,
  COALESCE((
    SELECT string_agg(DISTINCT p.provider, ', ' ORDER BY p.provider)
    FROM user_auth_providers p
    WHERE p.user_id = u.user_id
  ), '') AS auth_providers
FROM users u
ORDER BY u.user_id ASC
LIMIT $1 OFFSET $2
`

type ListUsersForAdminParams struct {
	Limit  int32
	Offset int32
}

type ListUsersForAdminRow struct {
	UserID        int64
	Name          string
	Email         *string
	CreatedAt     pgtype.Timestamptz
	Role          string
	AuthProviders interface{}
}

func (q *Queries) ListUsersForAdmin(ctx context.Context, arg *ListUsersForAdminParams) ([]*ListUsersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersForAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListUsersForAdminRow
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Role,
			&i.AuthProviders,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotersByParticipant = `-- name: ListVotersByParticipant :many
SELECT
    cv.user_id,
    COALESCE(u.name, 'Пользователь ' || cv.user_id::text) AS user_name,
    cv.created_at
FROM contest_votes cv
LEFT JOIN users u ON u.user_id = cv.user_id
WHERE cv.contest_id = $1 AND cv.participant_id = $2
ORDER BY cv.created_at ASC
`

type ListVotersByParticipantParams struct {
	ContestID     pgtype.UUID
	ParticipantID pgtype.UUID
}

type ListVotersByParticipantRow struct {
	UserID    int64
	UserName  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListVotersByParticipant(ctx context.Context, arg *ListVotersByParticipantParams) ([]*ListVotersByParticipantRow, error) {
	rows, err := q.db.Query(ctx, listVotersByParticipant, arg.ContestID, arg.ParticipantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListVotersByParticipantRow
	for rows.Next() {
		var i ListVotersByParticipantRow
		if err := rows.Scan(&i.UserID, &i.UserName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markParticipantSubmissionPending = `-- name: MarkParticipantSubmissionPending :exec
UPDATE contest_participants
SET submission_status = 'pending', submission_comment = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkParticipantSubmissionPending(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markParticipantSubmissionPending, id)
	return err
}

const searchUsersByQuery = `-- name: SearchUsersByQuery :many
SELECT user_id, name, email
FROM users
WHERE (
    $1::text = '' OR
    name ILIKE '%' || $1 || '%' OR
    COALESCE(email, '') ILIKE '%' || $1 || '%'
)
ORDER BY user_id ASC
LIMIT $2
`

type SearchUsersByQueryParams struct {
	Column1 string
	Limit   int32
}

type SearchUsersByQueryRow struct {
	UserID int64
	Name   string
	Email  *string
}

func (q *Queries) SearchUsersByQuery(ctx context.Context, arg *SearchUsersByQueryParams) ([]*SearchUsersByQueryRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByQuery, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SearchUsersByQueryRow
	for rows.Next() {
		var i SearchUsersByQueryRow
		if err := rows.Scan(&i.UserID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setParticipantSubmissionStatus = `-- name: SetParticipantSubmissionStatus :one
UPDATE contest_participants
SET
    submission_status = $2,
    submission_comment = CASE
        WHEN $2 = 'accepted' THEN NULL
        ELSE NULLIF(btrim($3::text), '')
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, contest_id, user_id, pet_name, pet_description, created_at, updated_at, registration_answers, nomination_id, submission_status, submission_comment
`

type SetParticipantSubmissionStatusParams struct {
	ID               pgtype.UUID
	SubmissionStatus string
	Column3          string
}

type SetParticipantSubmissionStatusRow struct {
	ID                  pgtype.UUID
	ContestID           pgtype.UUID
	UserID              int64
	PetName             string
	PetDescription      string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	RegistrationAnswers []byte
	NominationID        pgtype.UUID
	SubmissionStatus    string
	SubmissionComment   *string
}

func (q *Queries) SetParticipantSubmissionStatus(ctx context.Context, arg *SetParticipantSubmissionStatusParams) (*SetParticipantSubmissionStatusRow, error) {
	row := q.db.QueryRow(ctx, setParticipantSubmissionStatus, arg.ID, arg.SubmissionStatus, arg.Column3)
	var i SetParticipantSubmissionStatusRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.PetName,
		&i.PetDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationAnswers,
		&i.NominationID,
		&i.SubmissionStatus,
		&i.SubmissionComment,
	)
	return &i, err
}

const setUserEmailIfEmpty = `-- name: SetUserEmailIfEmpty :exec
UPDATE users AS u SET email = $2
WHERE u.user_id = $1
  AND (u.email IS NULL OR btrim(COALESCE(u.email, '')) = '')
  AND NOT EXISTS (
    SELECT 1 FROM users u2
    WHERE u2.email = $2 AND u2.user_id <> u.user_id
  )
`

type SetUserEmailIfEmptyParams struct {
	UserID int64
	Email  *string
}

func (q *Queries) SetUserEmailIfEmpty(ctx context.Context, arg *SetUserEmailIfEmptyParams) error {
	_, err := q.db.Exec(ctx, setUserEmailIfEmpty, arg.UserID, arg.Email)
	return err
}

const sumJuryScoresByParticipantID = `-- name: SumJuryScoresByParticipantID :one
SELECT COALESCE(SUM(score), 0)::bigint
FROM contest_jury_scores
WHERE participant_id = $1
`

func (q *Queries) SumJuryScoresByParticipantID(ctx context.Context, participantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumJuryScoresByParticipantID, participantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumJuryScoresByParticipantIDs = `-- name: SumJuryScoresByParticipantIDs :many
SELECT participant_id, COALESCE(SUM(score), 0)::bigint AS total_score
FROM contest_jury_scores
WHERE participant_id = ANY($1::uuid[])
GROUP BY participant_id
`

type SumJuryScoresByParticipantIDsRow struct {
	ParticipantID pgtype.UUID
	TotalScore    int64
}

func (q *Queries) SumJuryScoresByParticipantIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]*SumJuryScoresByParticipantIDsRow, error) {
	rows, err := q.db.Query(ctx, sumJuryScoresByParticipantIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SumJuryScoresByParticipantIDsRow
	for rows.Next() {
		var i SumJuryScoresByParticipantIDsRow
		if err := rows.Scan(&i.ParticipantID, &i.TotalScore); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatMessage = `-- name: UpdateChatMessage :one
UPDATE contest_chat_messages
SET text = $1, updated_at = NOW()
WHERE id = $2 AND user_id = $3 AND is_system = FALSE
RETURNING id, contest_id, user_id, text, is_system, created_at, updated_at
`

type UpdateChatMessageParams struct {
	Text   string
	ID     pgtype.UUID
	UserID int64
}

func (q *Queries) UpdateChatMessage(ctx context.Context, arg *UpdateChatMessageParams) (*ContestChatMessage, error) {
	row := q.db.QueryRow(ctx, updateChatMessage, arg.Text, arg.ID, arg.UserID)
	var i ContestChatMessage
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.Text,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE contest_comments
SET text = $1, updated_at = NOW()
WHERE id = $2 AND user_id = $3
RETURNING id, participant_id, user_id, text, created_at, updated_at
`

type UpdateCommentParams struct {
	Text   string
	ID     pgtype.UUID
	UserID int64
}

func (q *Queries) UpdateComment(ctx context.Context, arg *UpdateCommentParams) (*ContestComment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.Text, arg.ID, arg.UserID)
	var i ContestComment
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateContest = `-- name: UpdateContest :one
UPDATE contests
SET
  title = $2,
  description = $3,
  public_voting_enabled = $4,
  jury_voting_enabled = $5,
  cover_url = $6,
  tagline = $7,
  rules_url = $8,
  prize_text = $9,
  logo_url = $10,
  theme_color = $11,
  sponsor_name = $12,
  sponsor_logo_url = $13,
  sponsor_url = $14,
  cta_label_override = $15,
  registration_starts_at = $16,
  voting_starts_at = $17,
  voting_ends_at = $18,
  participant_allowed_email_domains = $19,
  schedule_timezone = $20,
  updated_at = NOW()
WHERE id = $1
RETURNING id, created_by_user_id, title, description, status, created_at, updated_at, tier, cover_url, registration_starts_at, voting_starts_at, voting_ends_at, require_acceptance, public_voting_enabled, jury_voting_enabled, tagline, rules_url, prize_text, logo_url, theme_color, sponsor_name, sponsor_logo_url, sponsor_url, cta_label_override, participant_allowed_email_domains, schedule_timezone
`

type UpdateContestParams struct {
	ID                             pgtype.UUID
	Title                          string
	Description                    string
	PublicVotingEnabled            bool
	JuryVotingEnabled              bool
	CoverUrl                       string
	Tagline                        string
	RulesUrl                       string
	PrizeText                      string
	LogoUrl                        string
	ThemeColor                     string
	SponsorName                    string
	SponsorLogoUrl                 string
	SponsorUrl                     string
	CtaLabelOverride               string
	RegistrationStartsAt           pgtype.Timestamptz
	VotingStartsAt                 pgtype.Timestamptz
	VotingEndsAt                   pgtype.Timestamptz
	ParticipantAllowedEmailDomains string
	ScheduleTimezone               string
}

func (q *Queries) UpdateContest(ctx context.Context, arg *UpdateContestParams) (*Contest, error) {
	row := q.db.QueryRow(ctx, updateContest,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.PublicVotingEnabled,
		arg.JuryVotingEnabled,
		arg.CoverUrl,
		arg.Tagline,
		arg.RulesUrl,
		arg.PrizeText,
		arg.LogoUrl,
		arg.ThemeColor,
		arg.SponsorName,
		arg.SponsorLogoUrl,
		arg.SponsorUrl,
		arg.CtaLabelOverride,
		arg.RegistrationStartsAt,
		arg.VotingStartsAt,
		arg.VotingEndsAt,
		arg.ParticipantAllowedEmailDomains,
		arg.ScheduleTimezone,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.CoverUrl,
		&i.RegistrationStartsAt,
		&i.VotingStartsAt,
		&i.VotingEndsAt,
		&i.RequireAcceptance,
		&i.PublicVotingEnabled,
		&i.JuryVotingEnabled,
		&i.Tagline,
		&i.RulesUrl,
		&i.PrizeText,
		&i.LogoUrl,
		&i.ThemeColor,
		&i.SponsorName,
		&i.SponsorLogoUrl,
		&i.SponsorUrl,
		&i.CtaLabelOverride,
		&i.ParticipantAllowedEmailDomains,
		&i.ScheduleTimezone,
	)
	return &i, err
}

const updateContestStatus = `-- name: UpdateContestStatus :one
UPDATE contests
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, created_by_user_id, title, description, status, created_at, updated_at, tier, cover_url, registration_starts_at, voting_starts_at, voting_ends_at, require_acceptance, public_voting_enabled, jury_voting_enabled, tagline, rules_url, prize_text, logo_url, theme_color, sponsor_name, sponsor_logo_url, sponsor_url, cta_label_override, participant_allowed_email_domains, schedule_timezone
`

type UpdateContestStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateContestStatus(ctx context.Context, arg *UpdateContestStatusParams) (*Contest, error) {
	row := q.db.QueryRow(ctx, updateContestStatus, arg.ID, arg.Status)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.CoverUrl,
		&i.RegistrationStartsAt,
		&i.VotingStartsAt,
		&i.VotingEndsAt,
		&i.RequireAcceptance,
		&i.PublicVotingEnabled,
		&i.JuryVotingEnabled,
		&i.Tagline,
		&i.RulesUrl,
		&i.PrizeText,
		&i.LogoUrl,
		&i.ThemeColor,
		&i.SponsorName,
		&i.SponsorLogoUrl,
		&i.SponsorUrl,
		&i.CtaLabelOverride,
		&i.ParticipantAllowedEmailDomains,
		&i.ScheduleTimezone,
	)
	return &i, err
}

const updateNomination = `-- name: UpdateNomination :one
UPDATE contest_nominations
SET title = $3, description = $4, min_photo_count = $5
WHERE id = $1 AND contest_id = $2
RETURNING id, contest_id, title, description, sort_order, created_at, min_photo_count
`

type UpdateNominationParams struct {
	ID            pgtype.UUID
	ContestID     pgtype.UUID
	Title         string
	Description   string
	MinPhotoCount int32
}

func (q *Queries) UpdateNomination(ctx context.Context, arg *UpdateNominationParams) (*ContestNomination, error) {
	row := q.db.QueryRow(ctx, updateNomination,
		arg.ID,
		arg.ContestID,
		arg.Title,
		arg.Description,
		arg.MinPhotoCount,
	)
	var i ContestNomination
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.MinPhotoCount,
	)
	return &i, err
}

const updateParticipant = `-- name: UpdateParticipant :one
UPDATE contest_participants
SET pet_name = $2, pet_description = $3, registration_answers = $4, submission_status = 'pending', submission_comment = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, contest_id, user_id, pet_name, pet_description, created_at, updated_at, registration_answers, nomination_id, submission_status, submission_comment
`

type UpdateParticipantParams struct {
	ID                  pgtype.UUID
	PetName             string
	PetDescription      string
	RegistrationAnswers []byte
}

type UpdateParticipantRow struct {
	ID                  pgtype.UUID
	ContestID           pgtype.UUID
	UserID              int64
	PetName             string
	PetDescription      string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	RegistrationAnswers []byte
	NominationID        pgtype.UUID
	SubmissionStatus    string
	SubmissionComment   *string
}

func (q *Queries) UpdateParticipant(ctx context.Context, arg *UpdateParticipantParams) (*UpdateParticipantRow, error) {
	row := q.db.QueryRow(ctx, updateParticipant,
		arg.ID,
		arg.PetName,
		arg.PetDescription,
		arg.RegistrationAnswers,
	)
	var i UpdateParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.PetName,
		&i.PetDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RegistrationAnswers,
		&i.NominationID,
		&i.SubmissionStatus,
		&i.SubmissionComment,
	)
	return &i, err
}

const updateParticipantOwnerStaffCommentReadAt = `-- name: UpdateParticipantOwnerStaffCommentReadAt :exec
UPDATE contest_participants
SET owner_last_read_staff_comment_at = NOW(), updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdateParticipantOwnerStaffCommentReadAtParams struct {
	ID     pgtype.UUID
	UserID int64
}

func (q *Queries) UpdateParticipantOwnerStaffCommentReadAt(ctx context.Context, arg *UpdateParticipantOwnerStaffCommentReadAtParams) error {
	_, err := q.db.Exec(ctx, updateParticipantOwnerStaffCommentReadAt, arg.ID, arg.UserID)
	return err
}

const updateParticipantPhotoOrder = `-- name: UpdateParticipantPhotoOrder :exec
UPDATE contest_participant_photos
SET position = $3
WHERE participant_id = $1 AND id = $2
`

type UpdateParticipantPhotoOrderParams struct {
	ParticipantID pgtype.UUID
	ID            pgtype.UUID
	Position      int32
}

func (q *Queries) UpdateParticipantPhotoOrder(ctx context.Context, arg *UpdateParticipantPhotoOrderParams) error {
	_, err := q.db.Exec(ctx, updateParticipantPhotoOrder, arg.ParticipantID, arg.ID, arg.Position)
	return err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET name = $2
WHERE user_id = $1
RETURNING user_id, name, created_at, email, role
`

type UpdateUserNameParams struct {
	UserID int64
	Name   string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.UserID, arg.Name)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.Email,
		&i.Role,
	)
	return &i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2
WHERE user_id = $1
RETURNING user_id, name, created_at, email, role
`

type UpdateUserRoleParams struct {
	UserID int64
	Role   string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg *UpdateUserRoleParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.UserID, arg.Role)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.Email,
		&i.Role,
	)
	return &i, err
}

const upsertContestJuryScore = `-- name: UpsertContestJuryScore :one
INSERT INTO contest_jury_scores (id, participant_id, criterion_id, user_id, score, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (participant_id, criterion_id, user_id)
DO UPDATE SET score = EXCLUDED.score, updated_at = NOW()
RETURNING id, participant_id, criterion_id, user_id, score, created_at, updated_at
`

type UpsertContestJuryScoreParams struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	CriterionID   pgtype.UUID
	UserID        int64
	Score         int32
}

func (q *Queries) UpsertContestJuryScore(ctx context.Context, arg *UpsertContestJuryScoreParams) (*ContestJuryScore, error) {
	row := q.db.QueryRow(ctx, upsertContestJuryScore,
		arg.ID,
		arg.ParticipantID,
		arg.CriterionID,
		arg.UserID,
		arg.Score,
	)
	var i ContestJuryScore
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.CriterionID,
		&i.UserID,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertContestVote = `-- name: UpsertContestVote :one

INSERT INTO contest_votes (id, contest_id, participant_id, user_id, nomination_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (contest_id, user_id, nomination_slot) DO UPDATE
SET participant_id = EXCLUDED.participant_id, nomination_id = EXCLUDED.nomination_id, updated_at = NOW()
RETURNING id, contest_id, participant_id, user_id, nomination_id, created_at, updated_at, nomination_slot
`

type UpsertContestVoteParams struct {
	ID            pgtype.UUID
	ContestID     pgtype.UUID
	ParticipantID pgtype.UUID
	UserID        int64
	NominationID  pgtype.UUID
}

// Contest Votes
func (q *Queries) UpsertContestVote(ctx context.Context, arg *UpsertContestVoteParams) (*ContestVote, error) {
	row := q.db.QueryRow(ctx, upsertContestVote,
		arg.ID,
		arg.ContestID,
		arg.ParticipantID,
		arg.UserID,
		arg.NominationID,
	)
	var i ContestVote
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ParticipantID,
		&i.UserID,
		&i.NominationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NominationSlot,
	)
	return &i, err
}

const upsertParticipantVideo = `-- name: UpsertParticipantVideo :one

INSERT INTO contest_participant_videos (id, participant_id, url)
VALUES ($1, $2, $3)
ON CONFLICT (participant_id) DO UPDATE
SET id = EXCLUDED.id, url = EXCLUDED.url, created_at = NOW()
RETURNING id, participant_id, url, created_at
`

type UpsertParticipantVideoParams struct {
	ID            pgtype.UUID
	ParticipantID pgtype.UUID
	Url           string
}

// Contest Participant Videos
func (q *Queries) UpsertParticipantVideo(ctx context.Context, arg *UpsertParticipantVideoParams) (*ContestParticipantVideo, error) {
	row := q.db.QueryRow(ctx, upsertParticipantVideo, arg.ID, arg.ParticipantID, arg.Url)
	var i ContestParticipantVideo
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Url,
		&i.CreatedAt,
	)
	return &i, err
}

const upsertPhotoLike = `-- name: UpsertPhotoLike :one

INSERT INTO photo_likes (id, photo_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (photo_id, user_id) DO UPDATE
SET id = photo_likes.id
RETURNING id, photo_id, user_id, created_at
`

type UpsertPhotoLikeParams struct {
	ID      pgtype.UUID
	PhotoID pgtype.UUID
	UserID  int64
}

// Photo Likes
func (q *Queries) UpsertPhotoLike(ctx context.Context, arg *UpsertPhotoLikeParams) (*PhotoLike, error) {
	row := q.db.QueryRow(ctx, upsertPhotoLike, arg.ID, arg.PhotoID, arg.UserID)
	var i PhotoLike
	err := row.Scan(
		&i.ID,
		&i.PhotoID,
		&i.UserID,
		&i.CreatedAt,
	)
	return &i, err
}
