// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Contest Participant Photos
	AddParticipantPhoto(ctx context.Context, arg *AddParticipantPhotoParams) (*ContestParticipantPhoto, error)
	AddUserAuthProviders(ctx context.Context, arg *AddUserAuthProvidersParams) (*UserAuthProvider, error)
	CountChatMessages(ctx context.Context, contestID pgtype.UUID) (int64, error)
	CountCommentsByParticipant(ctx context.Context, participantID pgtype.UUID) (int64, error)
	CountContestJuryCriteria(ctx context.Context, contestID pgtype.UUID) (int64, error)
	CountContestJuryMembers(ctx context.Context, contestID pgtype.UUID) (int64, error)
	CountContests(ctx context.Context, dollar_1 string) (int64, error)
	// Сколько членов жюри выставили баллы по всем критериям конкурса для каждой заявки.
	CountJuryFullyScoredJurorsByParticipantIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]*CountJuryFullyScoredJurorsByParticipantIDsRow, error)
	CountNominationsByContest(ctx context.Context, contestID pgtype.UUID) (int64, error)
	CountParticipantsByContest(ctx context.Context, arg *CountParticipantsByContestParams) (int64, error)
	CountSystemAdmins(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountVotesByContest(ctx context.Context, contestID pgtype.UUID) (int64, error)
	CountVotesByContests(ctx context.Context, dollar_1 []pgtype.UUID) ([]*CountVotesByContestsRow, error)
	CountVotesByParticipant(ctx context.Context, participantID pgtype.UUID) (int64, error)
	// Contest Chat Messages
	CreateChatMessage(ctx context.Context, arg *CreateChatMessageParams) (*ContestChatMessage, error)
	// Contest Comments
	CreateComment(ctx context.Context, arg *CreateCommentParams) (*ContestComment, error)
	// Contests
	CreateContest(ctx context.Context, arg *CreateContestParams) (*Contest, error)
	// Contest nominations (категории; без шкал — шкалы только у критериев конкурса)
	CreateNomination(ctx context.Context, arg *CreateNominationParams) (*ContestNomination, error)
	// Contest Participants
	CreateParticipant(ctx context.Context, arg *CreateParticipantParams) (*CreateParticipantRow, error)
	// Users
	CreateUser(ctx context.Context, arg *CreateUserParams) (*CreateUserRow, error)
	DeleteChatMessage(ctx context.Context, arg *DeleteChatMessageParams) (pgtype.UUID, error)
	DeleteChatMessagesByUserID(ctx context.Context, userID int64) error
	DeleteComment(ctx context.Context, id pgtype.UUID) error
	DeleteCommentsByParticipant(ctx context.Context, participantID pgtype.UUID) error
	DeleteContest(ctx context.Context, id pgtype.UUID) error
	DeleteContestCommentsByUserID(ctx context.Context, userID int64) error
	DeleteContestJuryMember(ctx context.Context, arg *DeleteContestJuryMemberParams) error
	DeleteContestJuryMembersByUserID(ctx context.Context, userID int64) error
	DeleteContestVoteByUserAndNomination(ctx context.Context, arg *DeleteContestVoteByUserAndNominationParams) (pgtype.UUID, error)
	DeleteContestVotesByUserID(ctx context.Context, userID int64) error
	DeleteJuryCriteriaByContest(ctx context.Context, contestID pgtype.UUID) error
	DeleteJuryCriterionForContest(ctx context.Context, arg *DeleteJuryCriterionForContestParams) error
	DeleteNomination(ctx context.Context, id pgtype.UUID) error
	DeleteParticipant(ctx context.Context, id pgtype.UUID) error
	DeleteParticipantConsentAuditsForUser(ctx context.Context, userID int64) error
	DeleteParticipantPhoto(ctx context.Context, id pgtype.UUID) error
	DeletePaymentsByUserID(ctx context.Context, userID int64) error
	DeleteRegistrationFieldsByContest(ctx context.Context, contestID pgtype.UUID) error
	DeleteUser(ctx context.Context, userID int64) error
	DeleteUserAuthProvidersByUserID(ctx context.Context, userID int64) error
	DeleteVotesByParticipant(ctx context.Context, participantID pgtype.UUID) error
	GetCommentByID(ctx context.Context, id pgtype.UUID) (*ContestComment, error)
	GetContestByID(ctx context.Context, id pgtype.UUID) (*Contest, error)
	GetContestJuryMemberWithName(ctx context.Context, arg *GetContestJuryMemberWithNameParams) (*GetContestJuryMemberWithNameRow, error)
	GetContestVoteForUserNominationSlot(ctx context.Context, arg *GetContestVoteForUserNominationSlotParams) (*ContestVote, error)
	GetMaxPhotoPositionByParticipant(ctx context.Context, participantID pgtype.UUID) (interface{}, error)
	GetNominationByContest(ctx context.Context, arg *GetNominationByContestParams) (*ContestNomination, error)
	GetParticipantByContestUserAndNomination(ctx context.Context, arg *GetParticipantByContestUserAndNominationParams) (*GetParticipantByContestUserAndNominationRow, error)
	GetParticipantByID(ctx context.Context, id pgtype.UUID) (*GetParticipantByIDRow, error)
	GetPhotosByParticipantID(ctx context.Context, participantID pgtype.UUID) ([]*ContestParticipantPhoto, error)
	GetUserAuthProvidersByProviderUid(ctx context.Context, arg *GetUserAuthProvidersByProviderUidParams) (*UserAuthProvider, error)
	GetUserAuthProvidersByUserID(ctx context.Context, userID int64) ([]*UserAuthProvider, error)
	GetUserByID(ctx context.Context, userID int64) (*GetUserByIDRow, error)
	GetUserRole(ctx context.Context, userID int64) (string, error)
	InsertContestJuryMember(ctx context.Context, arg *InsertContestJuryMemberParams) (*ContestJuryMember, error)
	InsertJuryCriterion(ctx context.Context, arg *InsertJuryCriterionParams) (*ContestJuryCriterium, error)
	InsertParticipantConsentAudit(ctx context.Context, arg *InsertParticipantConsentAuditParams) error
	InsertRegistrationField(ctx context.Context, arg *InsertRegistrationFieldParams) (*InsertRegistrationFieldRow, error)
	IsContestJuryMember(ctx context.Context, arg *IsContestJuryMemberParams) (bool, error)
	IsUserBlocked(ctx context.Context, userID int64) (bool, error)
	ListAcceptedParticipantScoresForContest(ctx context.Context, contestID pgtype.UUID) ([]*ListAcceptedParticipantScoresForContestRow, error)
	ListAcceptedParticipantScoresForContests(ctx context.Context, dollar_1 []pgtype.UUID) ([]*ListAcceptedParticipantScoresForContestsRow, error)
	ListChatMessages(ctx context.Context, arg *ListChatMessagesParams) ([]*ListChatMessagesRow, error)
	ListCommentsByParticipant(ctx context.Context, arg *ListCommentsByParticipantParams) ([]*ListCommentsByParticipantRow, error)
	// Contest jury members
	ListContestJuryMembersWithNames(ctx context.Context, contestID pgtype.UUID) ([]*ListContestJuryMembersWithNamesRow, error)
	ListContestJuryScoresByParticipantAndUser(ctx context.Context, arg *ListContestJuryScoresByParticipantAndUserParams) ([]*ContestJuryScore, error)
	// Детальный отчёт по оценкам жюри для заявки (для организаторов конкурса).
	ListContestJuryScoresReportByParticipant(ctx context.Context, participantID pgtype.UUID) ([]*ListContestJuryScoresReportByParticipantRow, error)
	// Прогресс оценивания: каждая пара (работа × член жюри) и число выставленных критериев.
	ListContestJuryVotingProgressByContest(ctx context.Context, contestID pgtype.UUID) ([]*ListContestJuryVotingProgressByContestRow, error)
	ListContestVotesByUser(ctx context.Context, arg *ListContestVotesByUserParams) ([]*ContestVote, error)
	ListContests(ctx context.Context, arg *ListContestsParams) ([]*Contest, error)
	ListContestsForStatusAutomation(ctx context.Context) ([]*Contest, error)
	// Contest jury criteria (общие для всего конкурса)
	ListJuryCriteriaByContest(ctx context.Context, contestID pgtype.UUID) ([]*ContestJuryCriterium, error)
	ListNominationsByContest(ctx context.Context, contestID pgtype.UUID) ([]*ContestNomination, error)
	ListNominationsForContests(ctx context.Context, dollar_1 []pgtype.UUID) ([]*ContestNomination, error)
	ListParticipantIDsByUserID(ctx context.Context, userID int64) ([]pgtype.UUID, error)
	ListParticipantsByContest(ctx context.Context, arg *ListParticipantsByContestParams) ([]*ListParticipantsByContestRow, error)
	// Contest registration fields (поля заявки участника)
	ListRegistrationFieldsByContest(ctx context.Context, contestID pgtype.UUID) ([]*ListRegistrationFieldsByContestRow, error)
	ListStaffCommentNotificationsForUser(ctx context.Context, userID int64) ([]*ListStaffCommentNotificationsForUserRow, error)
	ListUsersForAdmin(ctx context.Context, arg *ListUsersForAdminParams) ([]*ListUsersForAdminRow, error)
	ListVotersByParticipant(ctx context.Context, arg *ListVotersByParticipantParams) ([]*ListVotersByParticipantRow, error)
	MarkParticipantSubmissionPending(ctx context.Context, id pgtype.UUID) error
	NextContestJurySortOrder(ctx context.Context, contestID pgtype.UUID) (int32, error)
	SearchUsersByQuery(ctx context.Context, arg *SearchUsersByQueryParams) ([]*SearchUsersByQueryRow, error)
	SetContestJuryMemberSortOrder(ctx context.Context, arg *SetContestJuryMemberSortOrderParams) error
	SetParticipantSubmissionStatus(ctx context.Context, arg *SetParticipantSubmissionStatusParams) (*SetParticipantSubmissionStatusRow, error)
	SetUserAvatarIfEmpty(ctx context.Context, arg *SetUserAvatarIfEmptyParams) error
	SetUserDateOfBirthIfEmpty(ctx context.Context, arg *SetUserDateOfBirthIfEmptyParams) error
	SetUserEmailIfEmpty(ctx context.Context, arg *SetUserEmailIfEmptyParams) error
	SetUserPhoneIfEmpty(ctx context.Context, arg *SetUserPhoneIfEmptyParams) error
	SumJuryScoresByParticipantID(ctx context.Context, participantID pgtype.UUID) (int64, error)
	SumJuryScoresByParticipantIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]*SumJuryScoresByParticipantIDsRow, error)
	SyncNominationPhotoCountsByContest(ctx context.Context, arg *SyncNominationPhotoCountsByContestParams) error
	UpdateChatMessage(ctx context.Context, arg *UpdateChatMessageParams) (*ContestChatMessage, error)
	UpdateComment(ctx context.Context, arg *UpdateCommentParams) (*ContestComment, error)
	UpdateContest(ctx context.Context, arg *UpdateContestParams) (*Contest, error)
	UpdateContestJuryMember(ctx context.Context, arg *UpdateContestJuryMemberParams) (*ContestJuryMember, error)
	UpdateContestStatus(ctx context.Context, arg *UpdateContestStatusParams) (*Contest, error)
	UpdateContestVotingResults(ctx context.Context, arg *UpdateContestVotingResultsParams) (*Contest, error)
	UpdateJuryCriterion(ctx context.Context, arg *UpdateJuryCriterionParams) (*ContestJuryCriterium, error)
	UpdateNomination(ctx context.Context, arg *UpdateNominationParams) (*ContestNomination, error)
	UpdateNominationLogoUrl(ctx context.Context, arg *UpdateNominationLogoUrlParams) (*ContestNomination, error)
	UpdateNominationSortOrder(ctx context.Context, arg *UpdateNominationSortOrderParams) (int64, error)
	UpdateParticipant(ctx context.Context, arg *UpdateParticipantParams) (*UpdateParticipantRow, error)
	UpdateParticipantOwnerStaffCommentReadAt(ctx context.Context, arg *UpdateParticipantOwnerStaffCommentReadAtParams) error
	UpdateParticipantPhotoOrder(ctx context.Context, arg *UpdateParticipantPhotoOrderParams) error
	UpdateUserBlocked(ctx context.Context, arg *UpdateUserBlockedParams) (*UpdateUserBlockedRow, error)
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*UpdateUserNameRow, error)
	UpdateUserProfile(ctx context.Context, arg *UpdateUserProfileParams) (*UpdateUserProfileRow, error)
	UpdateUserRole(ctx context.Context, arg *UpdateUserRoleParams) (*UpdateUserRoleRow, error)
	UpsertContestJuryScore(ctx context.Context, arg *UpsertContestJuryScoreParams) (*ContestJuryScore, error)
	// Contest Votes
	UpsertContestVote(ctx context.Context, arg *UpsertContestVoteParams) (*ContestVote, error)
}

var _ Querier = (*Queries)(nil)
